export let flex = css`display: flex; position: relative;`;
export const wevenly = css`justify-content: space-between`;
export const hcenter = css`align-items: center`;
export const wcenter = css`justify-content: center`;
export const col = css`flex-direction: column`;
export const h100 = css`height:100%`;
export const w100 = css`width:100%`;
export const clip = css`overflow: hidden`;
export const scrolly = css`overflow-y: scroll`;
export const borderbox = css`box-sizing: border-box`
export const gap = css`gap: 1em`
export const padding = css`padding: 1em`
export const inlineflex = css`display: inline-flex`
